name: Github Actions 

on:
  push:
    branches:
      - main

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Fist step in first_job
        run: echo "First step in first_job"

      - name: Second step in first_job
        run: echo "Second step in first_job" 

  second_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Fist step in second_job
        run: echo "First step in second_job"

      - name: Second step in second_job
        run: echo "Second step in second_job" 