name: Github Actions Access Secret and Variable

on:
  push:
    branches:
      - main

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Fist step in first_job
        run: echo "First step in first_job - get secret ${{ secrets.FIRST_SECRET }}"

      - name: Second step in first_job
        run: echo "Second step in first_job - get secret ${{ secrets.SECOND_SECRET }}" 
  
  second_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Fist step in second_job
        run: echo "First step in first_job - get secret ${{ env.FIRST_VARIABLE }}"

      - name: Second step in second_job
        run: echo "Second step in first_job - get secret ${{ env.SECOND_VARIABLE }}" 
